# Generated by Django 4.0.2 on 2023-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.CharField(max_length=20)),
                ('questionName', models.TextField()),
                ('link', models.TextField()),
                ('accptRate', models.CharField(max_length=20)),
                ('hardType', models.CharField(max_length=50)),
                ('questionType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetCodeNo', models.IntegerField()),
                ('userId', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=20)),
                ('timeComplexity', models.CharField(max_length=20)),
                ('spaceComplexity', models.CharField(max_length=20)),
                ('answerType', models.CharField(max_length=20)),
            ],
        ),
    ]
